name: Lint commits

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check commit
        uses: ahmadnassri/action-commit-lint@v1
